Makefile.uk: Remove -Werror compile flag
unikraft/lib-nginx pull request #10
Opened 2022-11-02 12:16 UTC by StefanJum

When building with Musl, `lib-nginx` gives
some warnings which break the build.
Until the warnings are resolved, the
-Werror flag should be removed.

Signed-off-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-11-09 19:23 UTC, eduardvintila approved these changes
Looks good, thanks!

Reviewed-by: Eduard Vintilă eduard.vintila47@gmail.com

2022-11-15 08:39 UTC, razvand requested changes
Hi, @StefanJum , could you make the commit description message format more humane? It seems to trim at 40 characters or something. 72/80 characters is OK, but 40 is too small.

2022-11-15 08:54 UTC, StefanJum commented
Done @razvand, I'll go through the other prs I opened and do the same

2022-11-15 11:00 UTC, razvand approved these changes
Thanks, @StefanJum 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-18 09:00 UTC, closed without merging